package com.projetpaparobin.frontend.agents.inputs;

public enum ETypeAction {

	IDLE, CREATING_ZONE, CREATING_EXTINGUISHER, SELECTED_ZONE_TEXT, SELECTED_EXTINGUISHER_TEXT, SELECTED_CORNER, SELECTED_EXTINGUISHER
	
}
