package com.projetpaparobin.frontend.agents.inputs;

public enum ETypeAction {

	IDLE, 
	
	CREATING_ZONE, CREATING_EXTINGUISHER, CREATING_COMMENT,
	
	SELECTED_CORNER, SELECTED_ZONE, SELECTED_ZONE_TEXT, SELECTED_ZONE_TEXT_RESIZE_CORNER, SELECTED_EXTINGUISHER_TEXT, SELECTED_EXTINGUISHER, SELECTED_COMMENT, SELECTED_CONNECTION
	
}
